import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['500', '700'],
  variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: '/brand/klipa-mark.svg'
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="id" className={`${spaceGrotesk.variable} h-full antialiased scroll-smooth`}>
      <body className={`${spaceGrotesk.className} min-h-full flex flex-col tracking-wide`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
